### PR TITLE
Added support for Elasticsearch and AWS OpenSearch

### PR DESCRIPTION
**Pull request by jacdsouza**
* Elasticsearch v7.17 and v8.5
* OpenSearch v2.4

### CODE REVIEW

**Review by marxjohnson — COMMENTED** [review]
Hi Jackson,
I just came across this issue while testing on Moodle 4.1, good to see you've already sorted it! I would be nice if you can add 7.17 and 8.5 to the list of tested versions in README.md

**Comment by catalyst-eu** [comment]
Hey @marxjohnson I have updated README.md

**Comment by marxjohnson** [comment]
The code looks OK to me but in testing I was only able to get indexing to run with Elasticsearch 7, Version 8 and OpenSearch gave me a "Failed to create index" error. I will look at this with Jackson to work out if I'm doing something wrong in the testing, or if it's a bug in the code.

**Comment by marxjohnson** [comment]
Thanks Jackson,
This change looks good to me. I have tested indexing and searching with Elasticsearch 7, 8 and Opensearch 2. All working fine. I've just kicked off the CI tests and if that's all green I'll merge this in.

**Pull request merged**
