### PR TITLE
Support Moodle 4.5

### PR DESCRIPTION
**Pull request by tuanngocnguyen**
Regards issue https://github.com/mattporritt/moodle-search_elastic/issues/130

### CODE REVIEW

**Comment by tuanngocnguyen** [comment]
Hi @mattporritt ,

Hope you are doing well.

I wonder if this PR can be reviewed some times soon if possible.
The AWS SDK has been integrated into Moodle core and we would like to make it independent from local_aws.
(This will need a separate branch for Moodle4.4+)

Regards,

**Comment by mattporritt** [comment]
Hi @tuanngocnguyen ,
Thanks for you work on this. Because we're changing the minimum supported version with this change. I've created a new branch: MOODLE_404_STABLE and cherry-picked your patch into it.  I've also updated the github CI, README and bumped the plugin version number.
I'll close this PR and the related issue, but this is now good ot go via the MOODLE_404_STABLE branch

Cheers,
Matt P

**Comment by tuanngocnguyen** [comment]
Hi @mattporritt ,

Thanks for your work.

Regards

**Comment by dmitriim** [comment]
Hi @mattporritt and @tuanngocnguyen 
Seem like there is a bit mess in the branch matrix that would be nice to fix if possible.

image

**Pull request closed without merging**
